on: push

name: Narrative Elixir Service

env:
  ELIXIR_VERSION: "1.9"
  OTP_VERSION: "22.2"

jobs:
  deps:
    runs-on: ubuntu-latest
    env:
      NARRATIVE_HEX_ORG_API_KEY: ${{ secrets.NARRATIVE_HEX_ORG_API_KEY }}
      MIX_ENV: test
    steps:
      - name: Checking out project
        uses: actions/checkout@v2
      - name: "Setting up Elixir"
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Signing into narrativeapp organisation on hex
        run: mix hex.organization auth narrativeapp --key $NARRATIVE_HEX_ORG_API_KEY
      - name: Downloading dependency cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-deps
      - run: mix deps.get
      - name: Uploading dependencies for other jobs
        uses: actions/upload-artifact@v2
        with:
          name: deps
          path: deps/

  build:
    runs-on: ubuntu-latest
    needs: ["deps"]
    env:
      MIX_ENV: test
    steps:
      - name: Checking out project
        uses: actions/checkout@v2
      - name: "Setting up Elixir"
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Downloading dependencies
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: deps/
      - name: Downloading build artifact cache
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build
      - name: Run `mix compile`
        run: mix compile
      - name: Uploading build artifacts for other jobs
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: _build/

  credo:
    runs-on: ubuntu-latest
    needs: ["deps", "build"]
    env:
      MIX_ENV: test
    steps:
      - name: Checking out project
        uses: actions/checkout@v2
      - name: "Setting up Elixir"
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Downloading dependencies
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: deps/
      - name: Downloading build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: _build/
      - name: Downloading service Credo configuration
        run: curl -sSL -o .credo.exs https://raw.githubusercontent.com/NarrativeApp/.github/master/workflow-templates/credo.exs
      - run: mix credo --strict

  formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out project
        uses: actions/checkout@v2
      - name: "Setting up Elixir"
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - run: mix format --check-formatted

  audit:
    runs-on: ubuntu-latest
    needs: ["deps"]
    env:
      NARRATIVE_HEX_ORG_API_KEY: ${{ secrets.NARRATIVE_HEX_ORG_API_KEY }}
      MIX_ENV: test
    steps:
      - name: Checking out project
        uses: actions/checkout@v2
      - name: "Setting up Elixir"
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - run: mix hex.organization auth narrativeapp --key $NARRATIVE_HEX_ORG_API_KEY
      - name: Downloading dependencies
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: deps/
      - run: mix hex.audit

  test:
    runs-on: ubuntu-latest
    needs: ["deps", "build"]
    container: ubuntu:latest
    env:
      MIX_ENV: test
    steps:
      - name: Checking out project
        uses: actions/checkout@v2
      - name: "Setting up Elixir"
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Downloading dependencies
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: deps/
      - name: Downloading build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: _build/
      - run: mix test
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  release:
    runs-on: ubuntu-latest
    needs: ["deps", "test", "audit", "formatter", "credo"]
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
    env:
      HEX_API_KEY: ${{ secrets.NARRATIVE_HEX_ORG_API_KEY }}
    steps:
      - name: Checking out project
        uses: actions/checkout@v2
      - name: Checking the tag version
        id: tag-version
        run: VERSION=$(basename ${{ github.ref }}) ; echo "::set-output name=tag-version::${VERSION:1}"
      - name: Checking the app version
        id: app-version
        run: "VERSION=$(awk -F\\\" '/version: /{print $2}' mix.exs); echo \"::set-output name=app-version::${VERSION}\""
      - name: Verifying that the git tag and the version in mix.exs match
        run: test "xx${{ steps.tag-version.outputs.tag-version }}" = "xx${{ steps.app-version.outputs.app-version }}"
      - name: Checking the app name
        id: app-name
        run: 'echo "::set-output name=app-name::$(awk -F''[:,]'' ''/app: /{print $3}'' mix.exs)"'
      - name: "Setting up Elixir"
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Downloading dependencies
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: deps/
      - name: Downloading build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: _build/
      - name: Creating new Github release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.app-version.outputs.app-version }}
          release_name: Release ${{ steps.app-name.outputs.app-name }} ${{ steps.app-version.outputs.app-version }}
          body: Autogenerated from tag push
